spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workout_db
    username: workout_sidik
    password: sidik123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update